import { DrumStick } from '../if.ts';

export const sticksCanopus: ReadonlyArray<DrumStick> = [
  // -- Signature --
  {
    name: 'CP-AI AHITO INAZAWA MODEL',
    part_number: 'CP-AI',
    maker: 'Canopus',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 410,
    diameter_mm: 13.8,
  },
  {
    name: 'CP-KK KUHARA KAZUYUKI MODEL',
    part_number: 'CP-KK',
    maker: 'Canopus',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'CP-YS3 Yasuo Sano Model #3',
    part_number: 'CP-YS3',
    maker: 'Canopus',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'CP-NK Noriyasu «Kaasuke» Kawamura Model',
    part_number: 'CP-NK',
    maker: 'Canopus',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.2,
  },
  {
    name: 'CP-KE Kazuhiro Ebisawa Model',
    part_number: 'CP-KE',
    maker: 'Canopus',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.5,
  },
  {
    name: 'CP-TH Kodachi',
    part_number: 'CP-TH',
    maker: 'Canopus',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 403,
    diameter_mm: 13.0,
  },
] as const;
