import { DrumStick } from '../if.ts';

// JPC オリジナルブランドらしい
export const sticksDrumCity: ReadonlyArray<DrumStick> = [
  {
    name: 'Stick Hickory Nylon',
    part_number: 'DCHN',
    maker: 'DrumCity',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: 'Stick Maple Nylon',
    part_number: 'DCMN',
    maker: 'DrumCity',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: 'Straight Ahead',
    part_number: 'DCSA',
    maker: 'DrumCity',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: 'Brew the sound hickory',
    part_number: 'DCBTSH',
    maker: 'DrumCity',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 397,
    diameter_mm: 12.6,
  },
  {
    name: 'Brew the sound maple',
    part_number: 'DCBTSM',
    maker: 'DrumCity',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 397,
    diameter_mm: 12.6,
  },
  {
    name: 'Honey Hunt Ride',
    part_number: 'DCHHR',
    maker: 'DrumCity',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.5,
  },
  {
    name: 'Big ear Mark2',
    part_number: 'Big ear Mark2',
    maker: 'DrumCity',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 407,
    diameter_mm: 15.5,
  },
] as const;
