import { DrumStick } from '../if.ts';
import { inchesToMillimeters } from '../StickUtils.ts';

export const sticksInnovativePercussion: ReadonlyArray<DrumStick> = [
  {
    name: 'Vintage Series 7A',
    part_number: 'Vintage Series 7A',
    maker: 'InnovativePercussion',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 13.5,
  },
  {
    name: 'Vintage Series 5A',
    part_number: 'Vintage Series 5A',
    maker: 'InnovativePercussion',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 14.3,
  },
  {
    name: 'Vintage Series 5AB',
    part_number: 'Vintage Series 5AB',
    maker: 'InnovativePercussion',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 14.7,
  },
  {
    name: 'Vintage Series 5B',
    part_number: 'Vintage Series 5B',
    maker: 'InnovativePercussion',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 15.1,
  },
  {
    name: 'Vintage Series 2B',
    part_number: 'Vintage Series 2B',
    maker: 'InnovativePercussion',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 412,
    diameter_mm: 16.0,
  },
  // --
  {
    name: 'Legacy Series L7A',
    part_number: 'Legacy Series L7A',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 13.5,
  },
  {
    name: 'Legacy Series L7AN',
    part_number: 'Legacy Series L7AN',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 13.5,
  },
  {
    name: 'Legacy Series LM7A',
    part_number: 'Legacy Series LM7A',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 13.5,
  },
  {
    name: 'Legacy Series L5A',
    part_number: 'Legacy Series L5A',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 14.3,
  },
  {
    name: 'Legacy Series L5AN',
    part_number: 'Legacy Series L5AN',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 14.3,
  },
  {
    name: 'Legacy Series LM5A',
    part_number: 'Legacy Series LM5A',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 14.3,
  },
  {
    name: 'Legacy Series L5AL',
    part_number: 'Legacy Series L5AL',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 14.3,
  },
  {
    name: 'Legacy Series L5ALN',
    part_number: 'Legacy Series L5ALN',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 14.3,
  },
  {
    name: 'Legacy Series L5AB',
    part_number: 'Legacy Series L5AB',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 14.7,
  },
  {
    name: 'Legacy Series L5ABN',
    part_number: 'Legacy Series L5ABN',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 14.7,
  },
  {
    name: 'Legacy Series L5B',
    part_number: 'Legacy Series L5B',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 15.1,
  },
  {
    name: 'Legacy Series L5BN',
    part_number: 'Legacy Series L5BN',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 15.1,
  },
  {
    name: 'Legacy Series LM5B',
    part_number: 'Legacy Series LM5B',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 15.1,
  },
  {
    name: 'Legacy Series L5BL',
    part_number: 'Legacy Series L5BL',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 15.1,
  },
  {
    name: 'Legacy Series L5BLN',
    part_number: 'Legacy Series L5BLN',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 15.1,
  },
  {
    name: 'Legacy Series L2B',
    part_number: 'Legacy Series L2B',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 412,
    diameter_mm: 16.0,
  },
  {
    name: 'Legacy Series L2BN',
    part_number: 'Legacy Series L2BN',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 412,
    diameter_mm: 16.0,
  },
  {
    name: 'Legacy Series L8A',
    part_number: 'Legacy Series L8A',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.2,
  },
  {
    name: 'Legacy Series L9A',
    part_number: 'Legacy Series L9A',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.7,
  },
  {
    name: 'Legacy Series L3A',
    part_number: 'Legacy Series L3A',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 411,
    diameter_mm: 14.8,
  },
  {
    name: 'Legacy Series L1A',
    part_number: 'Legacy Series L1A',
    maker: 'InnovativePercussion',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 425,
    diameter_mm: 15.0,
  },
  // -- Sig.
  {
    name: 'Jeff Hamilton Signature',
    part_number: 'JH-1',
    maker: 'InnovativePercussion',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 403,
    diameter_mm: 12.7,
  },
  // -- Innovation
  {
    name: 'Innovation Series Smooth Ride',
    part_number: 'SR',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 406,
    diameter_mm: 13.4,
  },
  {
    name: 'Innovation Series Cool Ride',
    part_number: 'CR',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 406,
    diameter_mm: 14.7,
  },
  {
    name: 'Innovation Series Hybrid',
    part_number: 'HB',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.7,
  },
  {
    name: 'Innovation Series Hybrid Nylon',
    part_number: 'HBN',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.7,
  },
  {
    name: 'Innovation Series Big Band',
    part_number: 'JZ',
    maker: 'InnovativePercussion',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.9,
  },
  {
    name: 'Innovation Series Rock',
    part_number: 'RK',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 15.6,
  },
  {
    name: 'Innovation Series Rock Nylon',
    part_number: 'RKN',
    maker: 'InnovativePercussion',
    tip_shape: 'Round',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 15.6,
  },
  {
    name: 'Innovation Series Nashville',
    part_number: 'BNA-1',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 15.8,
  },
  {
    name: 'Innovation Series LA Session',
    part_number: 'LAX-1',
    maker: 'InnovativePercussion',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 409,
    diameter_mm: 14.7,
  },
  // -- Field
  {
    name: 'Field Series FS-1',
    part_number: 'FS-1',
    maker: 'InnovativePercussion',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(17),
    diameter_mm: inchesToMillimeters(0.698),
  },
  {
    name: 'Field Series FS-2',
    part_number: 'FS-2',
    maker: 'InnovativePercussion',
    tip_shape: 'R_Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(17),
    diameter_mm: inchesToMillimeters(0.698),
  },
] as const;
