import { DrumStick } from '../if.ts';

export const sticksLerni: ReadonlyArray<DrumStick> = [
  {
    name: 'HICKORY STANDARD H-135KW',
    part_number: 'H-135KW',
    maker: 'Lerni',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 13.5,
  },
  {
    name: 'HICKORY STANDARD H-140AW',
    part_number: 'H-140AW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY STANDARD H-140ALW',
    part_number: 'H-140ALW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY STANDARD H-140BW',
    part_number: 'H-140BW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 412,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY STANDARD H-140RW',
    part_number: 'H-140RW',
    maker: 'Lerni',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY STANDARD H-140SW',
    part_number: 'H-140SW',
    maker: 'Lerni',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY STANDARD H-140KW',
    part_number: 'H-140KW',
    maker: 'Lerni',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 404,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY STANDARD H-145AW',
    part_number: 'H-145AW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'HICKORY STANDARD H-145RW',
    part_number: 'H-145RW',
    maker: 'Lerni',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'HICKORY STANDARD H-145KW',
    part_number: 'H-145KW',
    maker: 'Lerni',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'HICKORY STANDARD H-145MW',
    part_number: 'H-145MW',
    maker: 'Lerni',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'HICKORY STANDARD H-147MW',
    part_number: 'H-147MW',
    maker: 'Lerni',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 415,
    diameter_mm: 14.7,
  },
  {
    name: 'HICKORY STANDARD H-150AW',
    part_number: 'H-150AW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: 'HICKORY STANDARD H-150BW',
    part_number: 'H-150BW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  // Textured
  {
    name: 'HICKORY TEXTURE S-140AW',
    part_number: 'S-140AW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY TEXTURE S-140BW',
    part_number: 'S-140BW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 412,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY TEXTURE S-140LW TIPLESS',
    part_number: 'S-140LW TIPLESS',
    maker: 'Lerni',
    tip_shape: 'None',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'None',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'HICKORY TEXTURE S-145AW',
    part_number: 'S-145AW',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  // -- Signature. --
  {
    name: 'Spitz Tatsuo Sakiyama Model',
    part_number: 'H-145TS',
    maker: 'Lerni',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 408,
    diameter_mm: 14.5,
  },
  {
    name: 'BACK DROP BOMB MASUO Model',
    part_number: 'H-155MA MASUO ver.2',
    maker: 'Lerni',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 415,
    diameter_mm: 15.5,
  },
  {
    name: 'UVERworld SHINTARO Model ver.3',
    part_number: 'H-150SH',
    maker: 'Lerni',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: 'Fear, and Loathing in Las Vegas Tomonori Model',
    part_number: 'H-150RF',
    maker: 'Lerni',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 416,
    diameter_mm: 15.0,
  },
  {
    name: '04 Limited Sazabys KOHEI Model',
    part_number: 'H-152KO',
    maker: 'Lerni',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 408,
    diameter_mm: 15.2,
  },
  {
    name: 'coldrain Katsuma Model',
    part_number: 'H-155KT',
    maker: 'Lerni',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 402,
    diameter_mm: 15.5,
  },
  {
    name: 'FUZZY CONTROL SATOKO Model',
    part_number: 'S-137SSN',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.7,
  },
  {
    name: 'Hi-STANDARD Tsuneoka Model',
    part_number: 'S-140AT ツネオカ',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 404,
    diameter_mm: 14.0,
  },
  {
    name: 'Watanabe Yutaka Model',
    part_number: 'H-147YW',
    maker: 'Lerni',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 14.7,
  },
  {
    name: 'bobo Model',
    part_number: 'S-139BO',
    maker: 'Lerni',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 408,
    diameter_mm: 13.9,
  },
  {
    name: 'Yu Seki Model',
    part_number: 'H-142SY',
    maker: 'Lerni',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.2,
  },
  {
    name: 'Hideki Aoyama Model',
    part_number: 'H-152HA',
    maker: 'Lerni',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 407,
    diameter_mm: 15.2,
  },
] as const;
