import { DrumStick } from "../if.ts";

export const sticksLerni: ReadonlyArray<DrumStick> = [
    {
        name: "HICKORY STANDARD H-140AW",
        part_number: "H-140AW",
        maker: "Lerni",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.0,
    },
    {
        name: "HICKORY STANDARD H-140ALW",
        part_number: "H-140ALW",
        maker: "Lerni",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 419,
        diameter_mm: 14.0,
    },
    {
        name: "HICKORY STANDARD H-140BW",
        part_number: "H-140BW",
        maker: "Lerni",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 412,
        diameter_mm: 14.0,
    },
    {
        name: "HICKORY STANDARD H-140RW",
        part_number: "H-140RW",
        maker: "Lerni",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.0,
    },
    {
        name: "HICKORY STANDARD H-145AW",
        part_number: "H-145AW",
        maker: "Lerni",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.5,
    },
    {
        name: "HICKORY TEXTURE S-145AW",
        part_number: "S-145AW",
        maker: "Lerni",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.5,
    },
    {
        name: "Spitz Tatsuo Sakiyama Model",
        part_number: "H-145TS",
        maker: "Lerni",
        tip_shape: "Unknown",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 408,
        diameter_mm: 14.5,
    },
    {
        name: "UVERworld SHINTARO Model ver.3",
        part_number: "H-150SH",
        maker: "Lerni",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 15.0,
    },
    {
        name: "bobo Model",
        part_number: "S-139BO",
        maker: "Lerni",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 408,
        diameter_mm: 13.9,
    }
] as const;