import { DrumStick } from "../if.ts";

export const sticksLosCabos: ReadonlyArray<DrumStick> = [
    {
        name: "White Hickory 5A",
        part_number: "LCD5AH",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 14.6,
    },
    {
        name: "White Hickory 5B",
        part_number: "LCD5BH",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 15.2,
    },
    {
        name: "White Hickory 7A",
        part_number: "LCD7AH",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 394,
        diameter_mm: 13.8,
    },
    {
        name: "White Hickory 2B",
        part_number: "LCD2BH",
        maker: "LosCabos",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Long",
        length_mm: 413,
        diameter_mm: 16.0,
    },
    {
        name: "White Hickory 3A",
        part_number: "LCD3AH",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Long",
        length_mm: 413,
        diameter_mm: 14.9,
    },
    {
        name: "White Hickory 8A",
        part_number: "LCD8AH",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 14.7,
    },
    {
        name: "White Hickory Concert",
        part_number: "LCDCONH",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 413,
        diameter_mm: 16.1,
    },
    {
        name: "Red Hickory 5A",
        part_number: "LCD5ARH",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 14.6,
    },
    {
        name: "Red Hickory 5B",
        part_number: "LCD5BRH",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 15.2,
    },
    {
        name: "Red Hickory 7A",
        part_number: "LCD7ARH",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 394,
        diameter_mm: 13.8,
    },
    {
        name: "Red Hickory 2B",
        part_number: "LCD2BRH",
        maker: "LosCabos",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Long",
        length_mm: 413,
        diameter_mm: 16.0,
    },
    {
        name: "Red Hickory 3A",
        part_number: "LCD3ARH",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Long",
        length_mm: 413,
        diameter_mm: 14.9,
    },
    {
        name: "Red Hickory 8A",
        part_number: "LCD8ARH",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 14.7,
    },
    {
        name: "Red Hickory Jazz",
        part_number: "LCDJRH",
        maker: "LosCabos",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 413,
        diameter_mm: 14.6,
    },
    {
        name: "Red Hickory 55AB",
        part_number: "LCD55ABRH",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 406,
        diameter_mm: 14.9,
    },
    {
        name: "Red Hickory 77A",
        part_number: "LCD77ARH",
        maker: "LosCabos",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Long",
        length_mm: 414,
        diameter_mm: 14.5,
    },
    {
        name: "Red Hickory Rock",
        part_number: "LCDROCKRH",
        maker: "LosCabos",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 422,
        diameter_mm: 15.9,
    },
    {
        name: "Red Hickory 5A Intense",
        part_number: "LCD5AIRH",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 419,
        diameter_mm: 14.6,
    },
    {
        name: "Red Hickory Halftime",
        part_number: "LCM2",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 406,
        diameter_mm: 17.7,
    },
    {
        name: "Red Hickory Rally",
        part_number: "LCM3",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 431,
        diameter_mm: 17.4,
    },
    // -- Maple
    {
        name: "Maple 5A",
        part_number: "LCD5AM",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 14.6,
    },
    {
        name: "Maple 5B",
        part_number: "LCD5BM",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 15.2,
    },
    {
        name: "Maple 7A",
        part_number: "LCD7AM",
        maker: "LosCabos",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 394,
        diameter_mm: 13.8,
    },
    {
        name: "Maple 2B",
        part_number: "LCD2BM",
        maker: "LosCabos",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Maple",
        taper: "Long",
        length_mm: 413,
        diameter_mm: 16.0,
    },
    {
        name: "Maple 3A",
        part_number: "LCD3AM",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Long",
        length_mm: 413,
        diameter_mm: 14.9,
    },
    {
        name: "Maple 8A",
        part_number: "LCD8AM",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 14.7,
    },
    {
        name: "Maple Concert",
        part_number: "LCDCON",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 413,
        diameter_mm: 16.1,
    },
    {
        name: "Jive Maple",
        part_number: "LCDJIVE",
        maker: "LosCabos",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 413,
        diameter_mm: 14.1,
    }
] as const;