import { DrumStick } from "../if.ts";

export const sticksPearl: ReadonlyArray<DrumStick> = [
    {
        name: "Classic Series 7AC",
        part_number: "7AC",
        maker: "Pearl",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 397,
        diameter_mm: 13.0,
    },
    {
        name: "Classic Series 7ABC",
        part_number: "7ABC",
        maker: "Pearl",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 397,
        diameter_mm: 13.0,
    },
    {
        name: "Classic Series 7HC",
        part_number: "7HC",
        maker: "Pearl",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 397,
        diameter_mm: 13.0,
    },
    {
        name: "Classic Series 7HC-N",
        part_number: "7HC-N",
        maker: "Pearl",
        tip_shape: "Teardrop",
        tip_material: "Nylon",
        material: "Hickory",
        taper: "Medium",
        length_mm: 397,
        diameter_mm: 13.0,
    },
    {
        name: "Classic Series 7HBC",
        part_number: "7HBC",
        maker: "Pearl",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 397,
        diameter_mm: 13.0,
    },
    {
        name: "Classic Series 9AC",
        part_number: "9AC",
        maker: "Pearl",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 407,
        diameter_mm: 14.0,
    },
    {
        name: "Classic Series 9HC",
        part_number: "9HC",
        maker: "Pearl",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 407,
        diameter_mm: 14.0,
    },
    {
        name: "Classic Series 101AC",
        part_number: "101AC",
        maker: "Pearl",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 412,
        diameter_mm: 14.0,
    },
    {
        name: "Classic Series 101HC",
        part_number: "101HC",
        maker: "Pearl",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 412,
        diameter_mm: 14.0,
    },
    {
        name: "Classic Series 103AC",
        part_number: "103AC",
        maker: "Pearl",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 384,
        diameter_mm: 14.0,
    },
    {
        name: "Classic Series 103HC",
        part_number: "103HC",
        maker: "Pearl",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 384,
        diameter_mm: 14.0,
    },
    {
        name: "Classic Series 106AC",
        part_number: "106AC",
        maker: "Pearl",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Oak",
        taper: "Short",
        length_mm: 405,
        diameter_mm: 15.0,
    },
    {
        name: "Classic Series 106HC",
        part_number: "106HC",
        maker: "Pearl",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 405,
        diameter_mm: 15.0,
    },
    {
        name: "Classic Series 106HC-N",
        part_number: "106HC-N",
        maker: "Pearl",
        tip_shape: "Round",
        tip_material: "Nylon",
        material: "Hickory",
        taper: "Short",
        length_mm: 405,
        diameter_mm: 15.0,
    },
    {
        name: "Classic Series 106HBC",
        part_number: "106HBC",
        maker: "Pearl",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 405,
        diameter_mm: 15.0,
    },
    {
        name: "Classic Series 106MC",
        part_number: "106MC",
        maker: "Pearl",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Short",
        length_mm: 405,
        diameter_mm: 15.0,
    },
    {
        name: "Classic Series 110AC",
        part_number: "110AC",
        maker: "Pearl",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 398,
        diameter_mm: 14.5,
    },
    {
        name: "Classic Series 110HC",
        part_number: "110HC",
        maker: "Pearl",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 398,
        diameter_mm: 14.5,
    },
    {
        name: "Classic Series 110MC",
        part_number: "110MC",
        maker: "Pearl",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 398,
        diameter_mm: 14.5,
    },
    {
        name: "Classic Series 111AC",
        part_number: "111AC",
        maker: "Pearl",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 410,
        diameter_mm: 15,
    },
    {
        name: "Classic Series 111HC",
        part_number: "111HC",
        maker: "Pearl",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 410,
        diameter_mm: 15,
    },
    {
        name: "Classic Series 115HC",
        part_number: "115HC",
        maker: "Pearl",
        tip_shape: "None",
        tip_material: "Wood",
        material: "Hickory",
        taper: "None",
        length_mm: 405,
        diameter_mm: 14.5,
    },
    {
        name: "Classic Series 121HC",
        part_number: "121HC",
        maker: "Pearl",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 393,
        diameter_mm: 13.0,
    },
    {
        name: "Classic Series 122HC",
        part_number: "122HC",
        maker: "Pearl",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 389,
        diameter_mm: 14.0,
    },
    {
        name: "Classic Series 131AC",
        part_number: "131AC",
        maker: "Pearl",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 406,
        diameter_mm: 14.0,
    },
    {
        name: "Natural Series 7NH",
        part_number: "7NH",
        maker: "Pearl",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 397,
        diameter_mm: 13.0,
    },

    // Signature.
    {
        name: "Murakami Ponta Shu-ichi Signature",
        part_number: "132M",
        maker: "Pearl",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 395,
        diameter_mm: 15.0,
    }, {
        name: "Takahashi Makoto Signature",
        part_number: "105H",
        maker: "Pearl",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 404,
        diameter_mm: 16.0,
    },
    {
        name: "yukihiro Signature",
        part_number: "158H/4",
        maker: "Pearl",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Medium",
        length_mm: 394,
        diameter_mm: 14.5,
    },
    {
        name: "Tsunoda Hiro Signature",
        part_number: "176M",
        maker: "Pearl",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Short",
        length_mm: 405,
        diameter_mm: 16.0,
    },
    /// OTHER
    {
        name: "Training Stick 2S",
        part_number: "2S",
        maker: "Pearl",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Oak",
        taper: "Medium",
        length_mm: 433,
        diameter_mm: 16.0,
    },
    {
        name: "Training Stick 3S",
        part_number: "3S",
        maker: "Pearl",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Oak",
        taper: "Long",
        length_mm: 433,
        diameter_mm: 18.0,
    }
] as const;