import { DrumStick } from '../if.ts';

export const sticksPlaywood: ReadonlyArray<DrumStick> = [
  {
    name: 'O-14A',
    part_number: 'O-14A',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'O-14B',
    part_number: 'O-14B',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'O-14C',
    part_number: 'O-14C',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'O-14D',
    part_number: 'O-14D',
    maker: 'PLAYWOOD',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'O-14E',
    part_number: 'O-14E',
    maker: 'PLAYWOOD',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'H-14A',
    part_number: 'H-14A',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'H-14B',
    part_number: 'H-14B',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'H-14C',
    part_number: 'H-14C',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'H-14D',
    part_number: 'H-14D',
    maker: 'PLAYWOOD',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'H-14E',
    part_number: 'H-14E',
    maker: 'PLAYWOOD',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'M-14A',
    part_number: 'M-14A',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.5,
  },
  {
    name: 'M-14B',
    part_number: 'M-14B',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.5,
  },
  {
    name: 'M-14C',
    part_number: 'M-14C',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.5,
  },
  {
    name: 'M-14D',
    part_number: 'M-14D',
    maker: 'PLAYWOOD',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.5,
  },
  {
    name: 'M-14E',
    part_number: 'M-14E',
    maker: 'PLAYWOOD',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.5,
  },
  {
    name: 'M-15A',
    part_number: 'M-15A',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.0,
  },
  {
    name: 'M-15B',
    part_number: 'M-15B',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.0,
  },
  {
    name: 'M-15C',
    part_number: 'M-15C',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.0,
  },
  {
    name: 'M-15D',
    part_number: 'M-15D',
    maker: 'PLAYWOOD',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.0,
  },
  {
    name: 'M-15E',
    part_number: 'M-15E',
    maker: 'PLAYWOOD',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.0,
  },
  {
    name: 'M-16A',
    part_number: 'M-16A',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 16.0,
  },
  {
    name: 'M-16B',
    part_number: 'M-16B',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 16.0,
  },
  {
    name: 'M-16C',
    part_number: 'M-16C',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 16.0,
  },
  {
    name: 'M-16D',
    part_number: 'M-16D',
    maker: 'PLAYWOOD',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 16.0,
  },
  {
    name: 'M-16E',
    part_number: 'M-16E',
    maker: 'PLAYWOOD',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 16.0,
  },
  // -- Signature
  {
    name: 'Tatsuya Ishikawa Model',
    part_number: 'M-165-TTY',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 390,
    diameter_mm: 16.5,
  },
  {
    name: 'Tatsuya Ishikawa Model',
    part_number: 'M-175-TTY',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 390,
    diameter_mm: 17.5,
  },
  {
    name: 'Shigeru Mori Model',
    part_number: 'H-145SM',
    maker: 'PLAYWOOD',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 408,
    diameter_mm: 14.5,
  },
  {
    name: 'Hidehiko Kozai',
    part_number: 'M-165HK',
    maker: 'PLAYWOOD',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 385,
    diameter_mm: 16.5,
  },
  {
    name: 'Yoshitaka Kobayashi Model',
    part_number: 'H-16YK',
    maker: 'PLAYWOOD',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 385,
    diameter_mm: 16.0,
  },
  {
    name: 'Yoshitaka Kobayashi Model',
    part_number: 'GS-16YK',
    maker: 'PLAYWOOD',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'GoldenCitrine',
    taper: 'Long',
    length_mm: 385,
    diameter_mm: 16.0,
  },
] as const;
