import { inchesToMillimeters } from '../StickUtils.ts';
import { DrumStick } from '../if.ts';

export const sticksProMark: ReadonlyArray<DrumStick> = [
  {
    name: 'Forward 5A Hickory',
    part_number: 'TX5AW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 406.4,
    diameter_mm: 14.0,
  },
  {
    name: 'Forward 5A Long Hickory',
    part_number: 'TX5ALW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 419.1,
    diameter_mm: 14.0,
  },
  {
    name: 'Forward 7A Hickory',
    part_number: 'TX7AW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 390.5,
    diameter_mm: 13.0,
  },
  {
    name: 'Forward 7A Hickory Nylon',
    part_number: 'TX7AN',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 390.5,
    diameter_mm: 13.0,
  },
  // -- Raw と FireGrain はカットする。
  //   {
  //     name: 'Forward 7A Raw Hickory',
  //     part_number: 'TXR7AW',
  //     maker: 'ProMark',
  //     tip_shape: 'Oval',
  //     tip_material: 'Wood',
  //     material: 'Hickory',
  //     taper: 'Short',
  //     length_mm: 390.5,
  //     diameter_mm: 13.0,
  //   },
  //   {
  //     name: 'Forward 7A Raw Hickory, Nylon',
  //     part_number: 'TXR7AN',
  //     maker: 'ProMark',
  //     tip_shape: 'Oval',
  //     tip_material: 'Nylon',
  //     material: 'Hickory',
  //     taper: 'Short',
  //     length_mm: 390.5,
  //     diameter_mm: 13.0,
  //   },
  //   {
  //     name: 'Forward 7A FireGrain Hickory',
  //     part_number: 'TX7AW-FG',
  //     maker: 'ProMark',
  //     tip_shape: 'Oval',
  //     tip_material: 'Wood',
  //     material: 'Hickory',
  //     taper: 'Short',
  //     length_mm: 390.5,
  //     diameter_mm: 13.0,
  //   },

  {
    name: 'Forward 5B Hickory',
    part_number: 'TX5BW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 406.4,
    diameter_mm: 15.0,
  },
  {
    name: 'Forward 2B Hickory',
    part_number: 'TX2BW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 406.4,
    diameter_mm: 16.1,
  },
  {
    name: 'Forward 2B Hickory Nylon',
    part_number: 'TX2BN',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 406.4,
    diameter_mm: 16.1,
  },
  {
    name: 'Forward 747 Hickory',
    part_number: 'TX747W',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.551),
  },
  {
    name: 'Forward 747 Hickory Nylon',
    part_number: 'TX747N',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.551),
  },
  {
    name: 'Forward 747B Hickory',
    part_number: 'TX747BW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 3 / 4),
    diameter_mm: inchesToMillimeters(0.590),
  },
  {
    name: 'Forward 747B Hickory Nylon',
    part_number: 'TX747BN',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 3 / 4),
    diameter_mm: inchesToMillimeters(0.590),
  },
  // -- Rebound
  {
    name: 'Rebound 5A Hickory',
    part_number: 'RBH565AW',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.565),
  },
  {
    name: 'Rebound 5A Hickory Nylon',
    part_number: 'RBH565N',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.565),
  },
  // MEMO: Active Grip を入れると面倒だからやめとくことにする
  //   {
  //     name: 'Rebound 5A ActiveGrip Hickory',
  //     part_number: 'R5AAG',
  //     maker: 'ProMark',
  //     tip_shape: 'Acorn',
  //     tip_material: 'Wood',
  //     material: 'Hickory',
  //     taper: 'Long',
  //     length_mm: inchesToMillimeters(16),
  //     diameter_mm: inchesToMillimeters(0.565),
  //   },
  {
    name: 'Rebound 5A Long Hickory',
    part_number: 'RBH565LAW',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 2),
    diameter_mm: inchesToMillimeters(0.565),
  },
  {
    name: 'Rebound ７A Hickory',
    part_number: '',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.535),
  },
  {
    name: 'Rebound ７A Hickory Nylon',
    part_number: 'RBH535N',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.535),
  },
  {
    name: 'Rebound ７A Long Hickory',
    part_number: 'RBH535LAW',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 2),
    diameter_mm: inchesToMillimeters(0.535),
  },
  {
    name: 'Rebound 2B Hickory',
    part_number: 'RBH625AW',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.625),
  },
  {
    name: 'Rebound 2B Long Hickory',
    part_number: 'RBH625LAW',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 2),
    diameter_mm: inchesToMillimeters(0.625),
  },
  {
    name: 'Rebound 5B Hickory',
    part_number: '',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.595),
  },
  {
    name: 'Rebound 5B Hickory Nylon',
    part_number: 'RBH595N',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.595),
  },
  // -- Finesse
  {
    name: 'FINESSE 718 Hickory',
    part_number: 'TX718W',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: 14,
  },
  {
    name: 'Finesse 7A Maple',
    part_number: 'RBM565RW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: 406.4,
    diameter_mm: 13.5,
  },
  {
    name: 'Finesse 5A Maple',
    part_number: 'RBM565RW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: 406.4,
    diameter_mm: 14.4,
  },
  {
    name: 'Finesse 5A Long Maple',
    part_number: 'RBM565LRW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 2),
    diameter_mm: 14.4,
  },
  {
    name: 'Finesse 2B Maple',
    part_number: 'RBM625RW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: 406.4,
    diameter_mm: 15.9,
  },
  {
    name: 'Finesse 2B Long Maple',
    part_number: 'RBM625LRW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: 419.1,
    diameter_mm: 15.9,
  },
  {
    name: 'Finesse 5B Maple',
    part_number: 'RBM595RW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: 406.4,
    diameter_mm: 15.1,
  },
  {
    name: 'Finesse 5B Long Maple',
    part_number: 'RBM595LRW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 2),
    diameter_mm: 15.1,
  },
  // -- Oak
  {
    name: 'ATTACK 747B Shira Kashi Oak',
    part_number: 'PW747BW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 3 / 4),
    diameter_mm: inchesToMillimeters(0.590),
  },
  // -- SD
  {
    name: 'SD1W',
    part_number: 'SD1W',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 416,
    diameter_mm: 16.1,
  },
  {
    name: 'SD2W',
    part_number: 'SD2W',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400.1,
    diameter_mm: 16.1,
  },
  // -- Signature Series --
  {
    name: 'Mike Portnoy Hickory',
    part_number: 'TX420N',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 409.6,
    diameter_mm: 13.5,
  },
  {
    name: 'BILL BRUFORD Maple',
    part_number: 'SD4W',
    maker: 'ProMark',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'ExtraLong',
    length_mm: 403.2,
    diameter_mm: 13.5,
  },
  {
    name: 'Todd Sucherman Maple',
    part_number: 'SD330W',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 406.4,
    diameter_mm: 15.2,
  },
  {
    name: 'JASON BONHAM Maple',
    part_number: 'SD531W',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 425.5,
    diameter_mm: 15.1,
  },
  {
    name: 'Rudy Garcia Hickory',
    part_number: 'TXDCRGW',
    maker: 'ProMark',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 429.3,
    diameter_mm: 17.4,
  },
  {
    name: 'Anika Nilles Hickory',
    part_number: 'RBANW',
    maker: 'ProMark',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.545),
  },
  {
    name: 'Miguel Lamas Hickory',
    part_number: 'TXMLW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(15 + 37 / 40),
    diameter_mm: inchesToMillimeters(0.575),
  },
  {
    name: 'Dave Lombardo Hickory',
    part_number: 'TX2BXN',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 1 / 8),
    diameter_mm: inchesToMillimeters(0.630),
  },
  {
    name: 'Marco Minnemann Hickory',
    part_number: 'TX721W',
    maker: 'ProMark',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.571),
  },
  {
    name: 'Carter Mclean Hickory',
    part_number: 'RBCMW',
    maker: 'ProMark',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 8),
    diameter_mm: inchesToMillimeters(0.571),
  },
  {
    name: 'Simon Phillips Hickory',
    part_number: 'TX707W',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.551),
  },
  {
    name: 'Rick Latham Hickory',
    part_number: 'TX717W',
    maker: 'ProMark',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.551),
  },
  {
    name: 'Ian Paice Hickory',
    part_number: 'TX808LW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: inchesToMillimeters(16 + 1 / 8),
    diameter_mm: inchesToMillimeters(0.579),
  },
  {
    name: 'Elvin Jones Hickory',
    part_number: 'TXJZW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.512),
  },
  {
    name: 'Phil Collins Hickory',
    part_number: 'TXPCW',
    maker: 'ProMark',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(14 + 3 / 4),
    diameter_mm: inchesToMillimeters(0.579),
  },
  {
    name: 'Steve Ferrone Hickory',
    part_number: 'TX735W',
    maker: 'ProMark',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: inchesToMillimeters(16 + 13 / 16),
    diameter_mm: inchesToMillimeters(0.579),
  },
  {
    name: 'Neil Peart Shira Kashi Oak',
    part_number: 'TX735W',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.551),
  },
  // -- Other --
  {
    name: 'Concert One Orchestra',
    part_number: 'TXC1W',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 428.6,
    diameter_mm: 16.4,
  },
  {
    name: 'JUNIOR Hickory',
    part_number: 'TXJRW',
    maker: 'ProMark',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(13),
    diameter_mm: inchesToMillimeters(0.531),
  },
] as const;
