import { DrumStick } from "../if.ts";

export const sticksProMark: ReadonlyArray<DrumStick> = [
    {
        name: "Forward 7A Hickory",
        part_number: "TX7AW",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 390.5,
        diameter_mm: 13.0,
    },
    {
        name: "Forward 7A Hickory, Nylon",
        part_number: "TX7AN",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Nylon",
        material: "Hickory",
        taper: "Short",
        length_mm: 390.5,
        diameter_mm: 13.0,
    },
    {
        name: "Forward 7A Raw Hickory",
        part_number: "TXR7AW",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 390.5,
        diameter_mm: 13.0,
    },
    {
        name: "Forward 7A Raw Hickory, Nylon",
        part_number: "TXR7AN",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Nylon",
        material: "Hickory",
        taper: "Short",
        length_mm: 390.5,
        diameter_mm: 13.0,
    },
    {
        name: "Forward 7A FireGrain Hickory",
        part_number: "TX7AW-FG",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 390.5,
        diameter_mm: 13.0,
    },
    {
        name: "Forward 5A Hickory",
        part_number: "TX5AW",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 406.4,
        diameter_mm: 14.0,
    },
    {
        name: "Forward 5A Long Hickory",
        part_number: "TX5ALW",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 419.1,
        diameter_mm: 14.0,
    },
    {
        name: "Forward 5B Hickory",
        part_number: "TX5BW",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 406.4,
        diameter_mm: 15.0,
    },
    {
        name: "Forward 2B Hickory",
        part_number: "TX2BW",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Short",
        length_mm: 406.4,
        diameter_mm: 16.1,
    },
    {
        name: "Finesse 7A Maple",
        part_number: "RBM565RW",
        maker: "ProMark",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Long",
        length_mm: 406.4,
        diameter_mm: 13.5,
    },
    {
        name: "Finesse 5A Maple",
        part_number: "RBM565RW",
        maker: "ProMark",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Long",
        length_mm: 406.4,
        diameter_mm: 14.4,
    },
    {
        name: "Finesse 2B Maple",
        part_number: "RBM625RW",
        maker: "ProMark",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Long",
        length_mm: 406.4,
        diameter_mm: 15.9,
    },
    {
        name: "Finesse 2B Long Maple",
        part_number: "RBM625LRW",
        maker: "ProMark",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Long",
        length_mm: 419.1,
        diameter_mm: 15.9,
    },
    {
        name: "SD1W",
        part_number: "SD1W",
        maker: "ProMark",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 416,
        diameter_mm: 16.1,
    },
    {
        name: "SD2W",
        part_number: "SD2W",
        maker: "ProMark",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 400.1,
        diameter_mm: 16.1,
    },
    // -- Signature Series --
    {
        name: "Mike Portnoy Hickory",
        part_number: "TX420N",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Nylon",
        material: "Hickory",
        taper: "Medium",
        length_mm: 409.6,
        diameter_mm: 13.5,
    },
    {
        name: "BILL BRUFORD Maple",
        part_number: "SD4W",
        maker: "ProMark",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Maple",
        taper: "ExtraLong",
        length_mm: 403.2,
        diameter_mm: 13.5,
    },
    {
        name: "TODD SUCHERMAN Maple",
        part_number: "SD330W",
        maker: "ProMark",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 406.4,
        diameter_mm: 15.2,
    },
    {
        name: "JASON BONHAM Maple",
        part_number: "SD531W",
        maker: "ProMark",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Maple",
        taper: "Medium",
        length_mm: 425.5,
        diameter_mm: 15.1,
    },
    {
        name: "Rudy Garcia Hickory",
        part_number: "TXDCRGW",
        maker: "ProMark",
        tip_shape: "Unknown",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Long",
        length_mm: 429.3,
        diameter_mm: 17.4,
    },
    // -- Other --
    {
        name: "Concert One Orchestra",
        part_number: "TXC1W",
        maker: "ProMark",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Long",
        length_mm: 428.6,
        diameter_mm: 16.4,
    },
] as const;