import { DrumStick } from '../if.ts';

export const sticksPromuco: ReadonlyArray<DrumStick> = [
  {
    name: '5A',
    part_number: '18015A',
    maker: 'Promuco',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.4,
  },
  {
    name: '5A Nylon',
    part_number: '1801N5A',
    maker: 'Promuco',
    tip_shape: 'Barrel',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.4,
  },
  {
    name: '7A',
    part_number: '18017A',
    maker: 'Promuco',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 393,
    diameter_mm: 14,
  },
  {
    name: '7A Nylon',
    part_number: '1801N7A',
    maker: 'Promuco',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 393,
    diameter_mm: 14,
  },
  {
    name: '2B',
    part_number: '18012B',
    maker: 'Promuco',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 410,
    diameter_mm: 16.0,
  },
  {
    name: '2B Nylon',
    part_number: '1801N2B',
    maker: 'Promuco',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 410,
    diameter_mm: 16.0,
  },
  {
    name: '5B',
    part_number: '18015B',
    maker: 'Promuco',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.2,
  },
  {
    name: '5B Nylon',
    part_number: '1801N5B',
    maker: 'Promuco',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.2,
  },
  // -- Maple
  {
    name: '5A Maple',
    part_number: '18025A',
    maker: 'Promuco',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.4,
  },
  {
    name: '7A Maple',
    part_number: '18027A',
    maker: 'Promuco',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 393,
    diameter_mm: 14,
  },
  {
    name: '2B Maple',
    part_number: '18022B',
    maker: 'Promuco',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 410,
    diameter_mm: 16.0,
  },
  {
    name: '5B Maple',
    part_number: '18025B',
    maker: 'Promuco',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.2,
  },
  // -- Oak
  {
    name: '5A Oak',
    part_number: '18035A',
    maker: 'Promuco',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.4,
  },
  {
    name: '7A Oak',
    part_number: '18037A',
    maker: 'Promuco',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 393,
    diameter_mm: 14,
  },
  {
    name: '2B Oak',
    part_number: '18032B',
    maker: 'Promuco',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 410,
    diameter_mm: 16.0,
  },
  {
    name: '5B Oak',
    part_number: '18035B',
    maker: 'Promuco',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.2,
  },
  // -- Sig.
  {
    name: 'John Bonham Signature',
    part_number: '19015JB',
    maker: 'Promuco',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 410,
    diameter_mm: 15.0,
  },
] as const;
