import { DrumStick } from '../if.ts';

export const sticksRohema: ReadonlyArray<DrumStick> = [
  // Classic Series
  {
    name: '5A Speed Stick',
    part_number: '618099',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 14.3,
  },
  {
    name: '5A Stick Control',
    part_number: '618100',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 14.3,
  },
  {
    name: '5A Evolution',
    part_number: '618087',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 14.3,
  },
  {
    name: 'Classic 7A',
    part_number: '61325/2',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 395,
    diameter_mm: 13.8,
  },
  {
    name: 'Classic 5AB',
    part_number: '61326/2',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 410,
    diameter_mm: 14.8,
  },
  // Hornwood Series
  {
    name: 'Hornwood 7A',
    part_number: '61325/3',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Birch',
    taper: 'Unknown',
    length_mm: 395,
    diameter_mm: 13.8,
  },
  {
    name: 'Hornwood 5A',
    part_number: '61323/3',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Birch',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 14.3,
  },
  {
    name: 'Hornwood 12H',
    part_number: '61337/3',
    maker: 'Rohema',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Birch',
    taper: 'Unknown',
    length_mm: 415,
    diameter_mm: 13,
  },
  {
    name: 'Hornwood 8H',
    part_number: '61339/3',
    maker: 'Rohema',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Birch',
    taper: 'Unknown',
    length_mm: 415,
    diameter_mm: 13,
  },
  // -- Hornbeam Series
  {
    name: 'Hornbeam 7A',
    part_number: '61325/1',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hornbeam',
    taper: 'Unknown',
    length_mm: 395,
    diameter_mm: 13.8,
  },
  {
    name: 'Hornbeam 5A',
    part_number: '61323/1',
    maker: 'Rohema',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hornbeam',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 14.3,
  },
  {
    name: 'Hornbeam Rock 5B',
    part_number: '61320/1',
    maker: 'Rohema',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hornbeam',
    taper: 'Unknown',
    length_mm: 415,
    diameter_mm: 16,
  },
] as const;
