import { DrumStick } from '../if.ts';

export const sticksTama: ReadonlyArray<DrumStick> = [
  {
    name: 'Original Series Hickory 13mm Diameter',
    part_number: 'H213-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.0,
  },
  {
    name: 'Original Series Hickory 13mm Diameter',
    part_number: 'H213-P',
    maker: 'Tama',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.0,
  },
  {
    name: 'Original Series Hickory 14mm Diameter',
    part_number: 'H214-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'Original Series Hickory 14mm Diameter',
    part_number: 'H214-P',
    maker: 'Tama',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'Original Series Hickory 14.5mm Diameter',
    part_number: 'H2145-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'Original Series Hickory 14.5mm Diameter',
    part_number: 'H2145-P',
    maker: 'Tama',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'Original Series Hickory 15mm Diameter',
    part_number: 'H215-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: 'Original Series Hickory 15mm Diameter',
    part_number: 'H215-P',
    maker: 'Tama',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: 'Original Series Hickory 15.5mm Diameter',
    part_number: 'H2155-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.5,
  },
  {
    name: 'Original Series Hickory 15.5mm Diameter',
    part_number: 'H2155-T',
    maker: 'Tama',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.5,
  },
  {
    name: 'Original Series Hickory 16mm Diameter',
    part_number: 'H216-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 16.0,
  },
  // -- Oak
  {
    name: 'Original Series Oak 13mm Diameter',
    part_number: 'O213-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Oak',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.0,
  },
  // -- Maple
  {
    name: 'M-JAZZ',
    part_number: 'M-JAZZ',
    maker: 'Tama',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.0,
  },
  {
    name: 'M-JAZZ-2',
    part_number: 'M-JAZZ-2',
    maker: 'Tama',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: 393,
    diameter_mm: 14.0,
  },
  {
    name: 'M-JAZZ-3',
    part_number: 'M-JAZZ-3',
    maker: 'Tama',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 397,
    diameter_mm: 12.75,
  },
  {
    name: 'M-JAZZ-N',
    part_number: 'M-JAZZ-N',
    maker: 'Tama',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.0,
  },
  {
    name: 'Original Series Maple 14mm Diameter',
    part_number: 'M214-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'Original Series Maple 14.5mm Diameter',
    part_number: 'M2145-B',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  // -- Signature --
  {
    name: 'Soul Toul Model',
    part_number: 'H-SOUL',
    maker: 'Tama',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 398,
    diameter_mm: 14.0,
  },
  {
    name: 'Shishido Kavka Model',
    part_number: 'H-KVK',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: 'Yukihiro Takahashi Model',
    part_number: 'H-YT',
    maker: 'Tama',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: 'Nyango Star Model',
    part_number: 'M-NYAN',
    maker: 'Tama',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 405,
    diameter_mm: 15.0,
  },
  {
    name: 'Kin-Ichi Motegi Model',
    part_number: 'H-KMO',
    maker: 'Tama',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 385,
    diameter_mm: 14.0,
  },
  {
    name: 'YOSHIKI Model Matillo',
    part_number: 'H-YKM2',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Other',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 398,
    diameter_mm: 14.5,
  },
  {
    name: 'YOSHIKI Model Black',
    part_number: 'H-YKB2',
    maker: 'Tama',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 398,
    diameter_mm: 14.5,
  },
] as const;
