import { DrumStick } from "../if.ts";

export const sticksTama: ReadonlyArray<DrumStick> = [
    {
        name: "H214-B",
        part_number: "H214-B",
        maker: "Tama",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.0,
    },
    {
        name: "H214-P",
        part_number: "H214-P",
        maker: "Tama",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.0,
    },
    {
        name: "M-JAZZ",
        part_number: "M-JAZZ",
        maker: "Tama",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 13.0,
    },
    {
        name: "Original Series Maple 14mm Diameter",
        part_number: "M214-B",
        maker: "Tama",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.0,
    },
    // -- Signature --
    {
        name: "Soul Toul Model",
        part_number: "H-SOUL",
        maker: "Tama",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 398,
        diameter_mm: 14.0,
    },
    {
        name: "Shishido Kavka Model",
        part_number: "H-KVK",
        maker: "Tama",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 15.0,
    },
    {
        name: "Yukihiro Takahashi Model",
        part_number: "H-YT",
        maker: "Tama",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 15.0,
    },
    {
        name: "Nyango Star Model",
        part_number: "M-NYAN",
        maker: "Tama",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 405,
        diameter_mm: 15.0,
    }
] as const;