import { inchesToMillimeters } from '../StickUtils.ts';
import { DrumStick } from '../if.ts';

export const sticksVater: ReadonlyArray<DrumStick> = [
  {
    name: 'Fusion',
    part_number: 'VHFW',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 14.7,
  },
  {
    name: 'Sugar Maple Fusion',
    part_number: 'VSMFW',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 14.7,
  },
  {
    name: 'Sugar Maple Fusion Nylon',
    part_number: 'VSMFN',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Nylon',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 14.7,
  },
  {
    name: 'SugarMaple SD1 Concert General',
    part_number: 'VSMCW',
    maker: 'Vater',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 16.0,
  },
  {
    name: 'SD9',
    part_number: 'VHSD9W',
    maker: 'Vater',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.610),
  },
  {
    name: 'SugarMaple SD9',
    part_number: 'VSMSD9W',
    maker: 'Vater',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.610),
  },
  {
    name: 'Blazer',
    part_number: 'BLAZER',
    maker: 'Vater',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 413,
    diameter_mm: 15.5,
  },
  {
    name: 'Hammer',
    part_number: 'HAMMER',
    maker: 'Vater',
    tip_shape: 'None',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'None',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'Concert',
    part_number: 'VSMCW',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 16.0,
  },
  {
    name: 'SugarMaple Piccolo',
    part_number: 'VSMPW',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 16.0,
  },
  {
    name: 'SugarMaple Pianissimo',
    part_number: 'VSMPIANW',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Short',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.635),
  },
  {
    name: 'SugarMaple 7A',
    part_number: 'SM-7A',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 407,
    diameter_mm: 13.7,
  },
  {
    name: 'Super Jazz',
    part_number: 'VHSJW',
    maker: 'Vater',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.555),
  },
  {
    name: 'SugarMaple Super Jazz',
    part_number: 'VSMSJW',
    maker: 'Vater',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.555),
  },
  {
    name: 'Sweet Ride',
    part_number: 'SWEET RIDE',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.6,
  },
  // -- Gospel Series
  {
    name: 'Gospel Series 5A',
    part_number: 'VGS5AW',
    maker: 'Vater',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16 + 1 / 2),
    diameter_mm: inchesToMillimeters(0.555),
  },
  // -- Signature
  {
    name: `Chad Smith's Funk Blaster`,
    part_number: 'VHCHADW',
    maker: 'Vater',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 15.5,
    // Src : https://www.youtube.com/watch?v=x3PFIC2p2E8
  },
  {
    name: `Gajate's Sazon`,
    part_number: 'VHGAJEW',
    maker: 'Vater',
    tip_shape: 'None',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'None',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.460),
  },
  {
    name: `Tito De Gracia Model`,
    part_number: 'VHTDG',
    maker: 'Vater',
    tip_shape: 'None',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'None',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.500),
  },
  {
    name: `Karl Perazzo's Drumbale`,
    part_number: 'VHKARLW',
    maker: 'Vater',
    tip_shape: 'None',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(15 + 1 / 2),
    diameter_mm: inchesToMillimeters(0.520),
  },
  {
    name: 'Cora Coleman Model',
    part_number: 'VHCCDW',
    maker: 'Vater',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16 + 1 / 2),
    diameter_mm: inchesToMillimeters(0.530),
  },
  {
    name: 'Elise Trouw Model',
    part_number: 'VHETW',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.540),
  },
  {
    name: `Lil' John Roberts' Philly Style`,
    part_number: 'VHLJRW',
    maker: 'Vater',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16 + 1 / 8),
    diameter_mm: inchesToMillimeters(0.555),
  },
  {
    name: `The Stewart Copeland Standard`,
    part_number: 'VHSCSTD',
    maker: 'Vater',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.555),
  },
  {
    name: `Brian Frasier-Moore Model`,
    part_number: 'VHBFMW',
    maker: 'Vater',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16 + 1 / 2),
    diameter_mm: inchesToMillimeters(0.565),
  },
  {
    name: `Pocket Queen Model`,
    part_number: 'VHPQW',
    maker: 'Vater',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16 + 1 / 8),
    diameter_mm: inchesToMillimeters(0.570),
  },
  {
    name: `Mike Mangini Wicked Piston`,
    part_number: 'VHMMWP',
    maker: 'Vater',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16 + 3 / 4),
    diameter_mm: inchesToMillimeters(0.580),
  },
  {
    name: `Chad Sexton Model`,
    part_number: 'VHSEXTON',
    maker: 'Vater',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.580),
  },
  {
    name: `Josh Freese's H-220`,
    part_number: 'VHJOSHW',
    maker: 'Vater',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.580),
  },
  {
    name: `Taku Hirano Katana`,
    part_number: 'VHTHK',
    maker: 'Vater',
    tip_shape: 'None',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.585),
  },
  {
    name: `Cindy Blackman Santana Magic Wand`,
    part_number: 'VHCBSW',
    maker: 'Vater',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.585),
  },
  {
    name: `Jay Weinberg 908`,
    part_number: 'VHJW908',
    maker: 'Vater',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.585),
  },
  //   {
  //     name: `Derek Roddy Model`,
  //     part_number: 'VHDRW',
  //     maker: 'Vater',
  //     tip_shape: 'Acorn',
  //     tip_material: 'Wood',
  //     material: 'Hickory', // ？？
  //     taper: 'Unknown',
  //     length_mm: inchesToMillimeters(16),
  //     diameter_mm: inchesToMillimeters(0.585),
  //   },
  {
    name: `Jimmy Cobb Model`,
    part_number: 'VHJCW',
    maker: 'Vater',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.595),
  },
  {
    name: `Vinnie Colaiuta Model`,
    part_number: 'VHVCW',
    maker: 'Vater',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(15.938),
    diameter_mm: inchesToMillimeters(0.595),
  },
  {
    name: `Abe Cunningham’s Cool Breeze`,
    part_number: 'VHABECW',
    maker: 'Vater',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: inchesToMillimeters(16 + 5 / 8),
    diameter_mm: inchesToMillimeters(0.600),
  },
  {
    name: `Smitty Smith's Power Fusion`,
    part_number: 'VHSMTYW',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: inchesToMillimeters(16 + 1 / 4),
    diameter_mm: inchesToMillimeters(0.600),
  },
  {
    name: `Morgan Rose's Alien Freak`,
    part_number: 'VHMRAF',
    maker: 'Vater',
    tip_shape: 'None',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'None',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.610),
  },
  {
    name: `Mike Wengren Model`,
    part_number: 'VHMWN',
    maker: 'Vater',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Short',
    length_mm: inchesToMillimeters(17),
    diameter_mm: inchesToMillimeters(0.625),
  },
  {
    name: `Tim Alexander Model`,
    part_number: 'VMTAW',
    maker: 'Vater',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Short',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.635),
  },
  // -- siguature international
  {
    name: `Eguchi Nobuo's Wild Cat`,
    part_number: 'VHWCATW',
    maker: 'Vater',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(16),
    diameter_mm: inchesToMillimeters(0.550),
  },
  // -- Other
  {
    name: `Junior Model`,
    part_number: 'VMJRW',
    maker: 'Vater',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: inchesToMillimeters(13),
    diameter_mm: inchesToMillimeters(0.520),
  },
] as const;
