import { DrumStick } from "../if.ts";

export const sticksVater: ReadonlyArray<DrumStick> = [
    {
        name: "Funk Blaster Chad Smith Model",
        part_number: "VHCHADW",
        maker: "Vater",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 15.5,
        // Src : https://www.youtube.com/watch?v=x3PFIC2p2E8
    },
    {
        name: "Fusion",
        part_number: "VHFW",
        maker: "Vater",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.7,
    },
    {
        name: "SD1 Concert General",
        part_number: "SD1",
        maker: "Vater",
        tip_shape: "Barrel",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 419,
        diameter_mm: 16.0,
    },
    {
        name: "Blazer",
        part_number: "BLAZER",
        maker: "Vater",
        tip_shape: "Acorn",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 41.3,
        diameter_mm: 15.5,
    },
    {
        name: "Hammer",
        part_number: "HAMMER",
        maker: "Vater",
        tip_shape: "None",
        tip_material: "Wood",
        material: "Hickory",
        taper: "None",
        length_mm: 406,
        diameter_mm: 14.5,
    },
    {
        name: "Concert",
        part_number: "VSMCW",
        maker: "Vater",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 419,
        diameter_mm: 16.0,
    },
    {
        name: "Piccolo",
        part_number: "VSMPW",
        maker: "Vater",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 16.0,
    },
    {
        name: "SugarMaple 7A",
        part_number: "SM-7A",
        maker: "Vater",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 407,
        diameter_mm: 13.7,
    },
    {
        name: "SugarMaple Super Jazz",
        part_number: "VSMSJW",
        maker: "Vater",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Maple",
        taper: "Unknown",
        length_mm: 413,
        diameter_mm: 14.0,
    },
    {
        name: "Sweet Ride",
        part_number: "SWEET RIDE",
        maker: "Vater",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 13.6,
    }
] as const;