import { DrumStick } from "../if.ts";

export const sticksVirFirth: ReadonlyArray<DrumStick> = [
  {
    name: "American Classic 5A",
    part_number: "VIC-5A",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: "American Classic 5A BARREL TIP",
    part_number: "VIC-5ABRL",
    maker: "VicFirth",
    tip_shape: "Barrel",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: "American Classic 5B",
    part_number: "VIC-5B",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: "American Classic 7A",
    part_number: "VIC-7A",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 394,
    diameter_mm: 13.7,
  },
  {
    name: "AMERICAN CLASSIC 7ATN",
    part_number: "VIC-7ATN",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Nylon",
    material: "Hickory",
    taper: "Medium",
    length_mm: 394,
    diameter_mm: 13.7,
  },
  {
    name: "AMERICAN CUSTOM SD1 GENERAL",
    part_number: "VIC-SD1",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Maple",
    taper: "Short",
    length_mm: 417,
    diameter_mm: 16.1,
  },
  {
    name: "AMERICAN CUSTOM SD2 BOLERO",
    part_number: "VIC-SD2",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Maple",
    taper: "Short",
    length_mm: 401,
    diameter_mm: 16.1,
  },
  {
    name: "AMERICAN SOUND 5A",
    part_number: "VIC-AS5A",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: "AMERICAN SOUND 5B",
    part_number: "VIC-AS5B",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: "AMERICAN SOUND 7A",
    part_number: "VIC-AS7A",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 394,
    diameter_mm: 13.7,
  },
] as const;