import { DrumStick } from "../if.ts";

export const sticksVirFirth: ReadonlyArray<DrumStick> = [
  {
    name: "American Classic 3A",
    part_number: "VIC-3A",
    maker: "VicFirth",
    tip_shape: "Barrel",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Short",
    length_mm: 412,
    diameter_mm: 14.7,
  },
  {
    name: "American Classic 5A",
    part_number: "VIC-5A",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: "American Classic 5A NYLON",
    part_number: "VIC-5AN",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Nylon",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: "American Classic 5A BARREL TIP",
    part_number: "VIC-5ABRL",
    maker: "VicFirth",
    tip_shape: "Barrel",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: "American Classic 5B",
    part_number: "VIC-5B",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: "American Classic 5B NYLON",
    part_number: "VIC-5BN",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Nylon",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: "American Classic EXTREME 5B",
    part_number: "VIC-X5B",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 419,
    diameter_mm: 15.1,
  },
  {
    name: "American Classic 55A",
    part_number: "VIC-55A",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.7,
  },
  {
    name: "American Classic 7A",
    part_number: "VIC-7A",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 394,
    diameter_mm: 13.7,
  },
  {
    name: "American Classic 7A NYLON",
    part_number: "VIC-7AN",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Nylon",
    material: "Hickory",
    taper: "Medium",
    length_mm: 394,
    diameter_mm: 13.7,
  },
  {
    name: "American Classic 85A",
    part_number: "VIC-85A",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.0,
  },
  {
    name: "American Classic 8D",
    part_number: "VIC-8D",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 13.7,
  },
  // ATシリーズは、ノーマル＋木材加工の違いっぽいので、目的外としてリストから除外しとく。
  // {
  //   name: "AMERICAN CLASSIC 7AT",
  //   part_number: "VIC-7AT",
  //   maker: "VicFirth",
  //   tip_shape: "Teardrop",
  //   tip_material: "Wood",
  //   material: "Hickory",
  //   taper: "Medium",
  //   length_mm: 394,
  //   diameter_mm: 13.7,
  // },
  // {
  //   name: "AMERICAN CLASSIC 7ATN",
  //   part_number: "VIC-7ATN",
  //   maker: "VicFirth",
  //   tip_shape: "Teardrop",
  //   tip_material: "Nylon",
  //   material: "Hickory",
  //   taper: "Medium",
  //   length_mm: 394,
  //   diameter_mm: 13.7,
  // },
  {
    name: "American Classic Rock",
    part_number: "VIC-R",
    maker: "VicFirth",
    tip_shape: "Oval",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 423,
    diameter_mm: 16.0,
  },
  {
    name: "American Classic Metal",
    part_number: "VIC-M",
    maker: "VicFirth",
    tip_shape: "Oval",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 432,
    diameter_mm: 16.1,
  },
  {
    name: "American Classic Metal NYLON",
    part_number: "VIC-MN",
    maker: "VicFirth",
    tip_shape: "Oval",
    tip_material: "Nylon",
    material: "Hickory",
    taper: "Medium",
    length_mm: 432,
    diameter_mm: 16.1,
  },
  // AMERICAN CUSTOM
  {
    name: "AMERICAN CUSTOM SD1 GENERAL",
    part_number: "VIC-SD1",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Maple",
    taper: "Short",
    length_mm: 417,
    diameter_mm: 16.1,
  },
  {
    name: "AMERICAN CUSTOM SD2 BOLERO",
    part_number: "VIC-SD2",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Maple",
    taper: "Short",
    length_mm: 401,
    diameter_mm: 16.1,
  },
  {
    name: "AMERICAN CUSTOM SD4 COMBO",
    part_number: "VIC-SD4",
    maker: "VicFirth",
    tip_shape: "Barrel",
    tip_material: "Wood",
    material: "Maple",
    taper: "Medium",
    length_mm: 404,
    diameter_mm: 13.8,
  },
  {
    name: "AMERICAN CUSTOM SD9 DRIVER",
    part_number: "VIC-SD9",
    maker: "VicFirth",
    tip_shape: "Oval",
    tip_material: "Wood",
    material: "Maple",
    taper: "Medium",
    length_mm: 413,
    diameter_mm: 15.5,
  },
  {
    name: "AMERICAN CUSTOM SD10 SWINGER",
    part_number: "VIC-SD10",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Maple",
    taper: "Medium",
    length_mm: 409,
    diameter_mm: 15.5,
  },
  // HERITAGE
  {
    name: "AMERICAN HERITAGE 7A",
    part_number: "VIC-AH7A",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Maple",
    taper: "Medium",
    length_mm: 13.7,
    diameter_mm: 39.4,
  },
  {
    name: "AMERICAN HERITAGE 5A",
    part_number: "VIC-AH5A",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Maple",
    taper: "Medium",
    length_mm: 14.4,
    diameter_mm: 407,
  },
  {
    name: "AMERICAN HERITAGE 5B",
    part_number: "VIC-AH5B",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Maple",
    taper: "Medium",
    length_mm: 15.5,
    diameter_mm: 407,
  },
  // AMERICAN SOUND
  {
    name: "AMERICAN SOUND 5A",
    part_number: "VIC-AS5A",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: "AMERICAN SOUND 5B",
    part_number: "VIC-AS5B",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: "AMERICAN SOUND 7A",
    part_number: "VIC-AS7A",
    maker: "VicFirth",
    tip_shape: "Round",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Medium",
    length_mm: 394,
    diameter_mm: 13.7,
  },
  // Sig.
  {
    name: "Jojo Mayer Signature",
    part_number: "VIC-SJM",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Unknown",
    length_mm: 389,
    diameter_mm: 14.7,
  },
  {
    name: "Steve Gadd Signature",
    part_number: "VIC-SG",
    maker: "VicFirth",
    tip_shape: "Barrel",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Unknown",
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: "Steve Gadd Signature, Nylon Tip",
    part_number: "VIC-SGN",
    maker: "VicFirth",
    tip_shape: "Barrel",
    tip_material: "Nylon",
    material: "Hickory",
    taper: "Unknown",
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: "Dave Weckl Signature",
    part_number: "VIC-DW2",
    maker: "VicFirth",
    tip_shape: "Teardrop",
    tip_material: "Wood",
    material: "Hickory",
    taper: "Unknown",
    length_mm: 406,
    diameter_mm: 14.3,
  }
] as const;