import { inchesToMillimeters } from '../StickUtils.ts';
import { DrumStick } from '../if.ts';

export const sticksVirFirth: ReadonlyArray<DrumStick> = [
  {
    name: 'American Classic 3A',
    part_number: 'VIC-3A',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 412,
    diameter_mm: 14.7,
  },
  {
    name: 'American Classic 5A',
    part_number: 'VIC-5A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: 'American Classic 5A NYLON',
    part_number: 'VIC-5AN',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: 'American Classic 5A BARREL TIP',
    part_number: 'VIC-5ABRL',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: 'American Classic EXTREME 5A',
    part_number: 'VIC-X5A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 419,
    diameter_mm: 14.4,
  },
  {
    name: 'American Classic EXTREME 5A NYLON',
    part_number: 'VIC-X5AN',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 419,
    diameter_mm: 14.4,
  },
  {
    name: 'American Classic 5B',
    part_number: 'VIC-5B',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: 'American Classic 5B NYLON',
    part_number: 'VIC-5BN',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: 'American Classic EXTREME 5B',
    part_number: 'VIC-X5B',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 419,
    diameter_mm: 15.1,
  },
  {
    name: 'American Classic EXTREME 5B NYLON',
    part_number: 'VIC-X5BN',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 419,
    diameter_mm: 15.1,
  },
  {
    name: 'American Classic 55A',
    part_number: 'VIC-55A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 14.7,
  },
  {
    name: 'American Classic EXTREME 55A',
    part_number: 'VIC-X55A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 419,
    diameter_mm: 14.7,
  },
  {
    name: 'American Classic 7A',
    part_number: 'VIC-7A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 394,
    diameter_mm: 13.7,
  },
  {
    name: 'American Classic 7A NYLON',
    part_number: 'VIC-7AN',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 394,
    diameter_mm: 13.7,
  },
  {
    name: 'American Classic 85A',
    part_number: 'VIC-85A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 14.0,
  },
  {
    name: 'American Classic 8D',
    part_number: 'VIC-8D',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 13.7,
  },
  // ATシリーズは、ノーマル＋木材加工の違いっぽいので、目的外としてリストから除外しとく。
  // {
  //   name: "AMERICAN CLASSIC 7AT",
  //   part_number: "VIC-7AT",
  //   maker: "VicFirth",
  //   tip_shape: "Teardrop",
  //   tip_material: "Wood",
  //   material: "Hickory",
  //   taper: "Medium",
  //   length_mm: 394,
  //   diameter_mm: 13.7,
  // },
  // {
  //   name: "AMERICAN CLASSIC 7ATN",
  //   part_number: "VIC-7ATN",
  //   maker: "VicFirth",
  //   tip_shape: "Teardrop",
  //   tip_material: "Nylon",
  //   material: "Hickory",
  //   taper: "Medium",
  //   length_mm: 394,
  //   diameter_mm: 13.7,
  // },
  {
    name: 'American Classic Rock',
    part_number: 'VIC-R',
    maker: 'VicFirth',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 423,
    diameter_mm: 16.0,
  },
  {
    name: 'American Classic Metal',
    part_number: 'VIC-M',
    maker: 'VicFirth',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 432,
    diameter_mm: 16.1,
  },
  {
    name: 'American Classic Metal NYLON',
    part_number: 'VIC-MN',
    maker: 'VicFirth',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 432,
    diameter_mm: 16.1,
  },
  {
    name: 'American Classic NE1',
    part_number: 'VIC-NE1',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 406,
    diameter_mm: 14.7,
  },
  {
    name: 'American Classic HD4',
    part_number: 'VIC-HD4',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 403,
    diameter_mm: 13.5,
  },
  {
    name: 'American Classic HD9',
    part_number: 'VIC-HD9',
    maker: 'VicFirth',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 413,
    diameter_mm: 15.5,
  },
  {
    name: 'American Classic KIDSTICKS(BLUE)',
    part_number: 'VIC-KIDS',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 330,
    diameter_mm: 13.2,
  },
  {
    name: 'American Classic KIDSTICKS PINK',
    part_number: 'VIC-KIDSPINK',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 330,
    diameter_mm: 13.2,
  },
  // AMERICAN CUSTOM
  {
    name: 'AMERICAN CUSTOM SD1 GENERAL',
    part_number: 'VIC-SD1',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Short',
    length_mm: 417,
    diameter_mm: 16.1,
  },
  {
    name: 'AMERICAN CUSTOM SD1 JR.',
    part_number: 'VIC-SD1JR',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Short',
    length_mm: 395,
    diameter_mm: 15.6,
  },
  {
    name: 'AMERICAN CUSTOM SD2 BOLERO',
    part_number: 'VIC-SD2',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Short',
    length_mm: 401,
    diameter_mm: 16.1,
  },
  {
    name: 'AMERICAN CUSTOM SD4 COMBO',
    part_number: 'VIC-SD4',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 404,
    diameter_mm: 13.8,
  },
  {
    name: 'AMERICAN CUSTOM SD5 ECHO',
    part_number: 'VIC-SD5',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Long',
    length_mm: 400,
    diameter_mm: 17.0,
  },
  {
    name: 'AMERICAN CUSTOM SD9 DRIVER',
    part_number: 'VIC-SD9',
    maker: 'VicFirth',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 413,
    diameter_mm: 15.5,
  },
  {
    name: 'AMERICAN CUSTOM SD10 SWINGER',
    part_number: 'VIC-SD10',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 409,
    diameter_mm: 15.5,
  },
  {
    name: 'AMERICAN CUSTOM SD12 SWIZZLE',
    part_number: 'VIC-SD12',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Short',
    length_mm: 422,
    diameter_mm: 16.1,
  },
  // HERITAGE
  {
    name: 'AMERICAN HERITAGE 7A',
    part_number: 'VIC-AH7A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 394,
    diameter_mm: 13.7,
  },
  {
    name: 'AMERICAN HERITAGE 5A',
    part_number: 'VIC-AH5A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: 'AMERICAN HERITAGE 5B',
    part_number: 'VIC-AH5B',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 15.5,
  },
  // FreeStyle
  {
    name: 'FREESTYLE 7A',
    part_number: 'VIC-FS7A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 432,
    diameter_mm: 13.7,
  },
  {
    name: 'FREESTYLE 5A',
    part_number: 'VIC-FS5A',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 432,
    diameter_mm: 14.4,
  },
  // American Jazz
  {
    name: 'AMERICAN JAZZ 1',
    part_number: 'VIC-AJ1',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: 'AMERICAN JAZZ 2',
    part_number: 'VIC-AJ2',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: 'AMERICAN JAZZ 3',
    part_number: 'VIC-AJ3',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 407,
    diameter_mm: 13.7,
  },
  {
    name: 'AMERICAN JAZZ 4',
    part_number: 'VIC-AJ4',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 407,
    diameter_mm: 13.2,
  },
  {
    name: 'AMERICAN JAZZ 5',
    part_number: 'VIC-AJ5',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 407,
    diameter_mm: 12.5,
  },
  {
    name: 'AMERICAN JAZZ 6',
    part_number: 'VIC-AJ6',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 394,
    diameter_mm: 14.0,
  },
  // AMERICAN SOUND
  {
    name: 'AMERICAN SOUND 5A',
    part_number: 'VIC-AS5A',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 14.4,
  },
  {
    name: 'AMERICAN SOUND 5B',
    part_number: 'VIC-AS5B',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: 'AMERICAN SOUND 7A',
    part_number: 'VIC-AS7A',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 394,
    diameter_mm: 13.7,
  },
  {
    name: 'AMERICAN SOUND 8D',
    part_number: 'VIC-AS8D',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 13.7,
  },
  // Symphonic Collection
  {
    name: 'SYMPHONIC COLLECTION GREG ZUBER EXCALIBUR',
    part_number: 'VIC-SGZE',
    maker: 'VicFirth',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Birch',
    taper: 'Long',
    length_mm: inchesToMillimeters(17),
    diameter_mm: inchesToMillimeters(0.675),
  },
  {
    name: 'SYMPHONIC COLLECTION GREG ZUBER NOTHUNG',
    part_number: 'VIC-SGZN',
    maker: 'VicFirth',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Birch',
    taper: 'Long',
    length_mm: inchesToMillimeters(17),
    diameter_mm: inchesToMillimeters(0.675),
  },
  {
    name: 'SYMPHONIC COLLECTION NEY ROSAURO',
    part_number: 'VIC-SNR',
    maker: 'VicFirth',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: inchesToMillimeters(16.5),
    diameter_mm: inchesToMillimeters(0.600),
  },
  {
    name: 'SYMPHONIC COLLECTION TOM GAUGER',
    part_number: 'VIC-TG15',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: inchesToMillimeters(16 + 9 / 16),
    diameter_mm: inchesToMillimeters(0.625),
  },
  {
    name: 'SYMPHONIC COLLECTION TED ATKATZ II',
    part_number: 'VIC-SATK2',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Nylon',
    material: 'Birch',
    taper: 'Short',
    length_mm: inchesToMillimeters(15 + 7 / 8),
    diameter_mm: inchesToMillimeters(0.605),
  },
  // Sig.
  {
    name: 'Jojo Mayer Signature',
    part_number: 'VIC-SJM',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 389,
    diameter_mm: 14.7,
  },
  {
    name: 'Steve Gadd Signature',
    part_number: 'VIC-SG',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'Steve Gadd Signature, Nylon Tip',
    part_number: 'VIC-SGN',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 14.0,
  },
  {
    name: 'Dave Weckl Signature',
    part_number: 'VIC-DW2',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.3,
  },
  {
    name: 'Nate Smith Signature',
    part_number: 'VIC-SNS',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 13.6,
  },
  {
    name: 'Peter Erskine Signature',
    part_number: 'VIC-PE',
    maker: 'VicFirth',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 13.3,
  },
  {
    name: 'Benny Greb Signature',
    part_number: 'VIC-SBG',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 407,
    diameter_mm: 15.1,
  },
  {
    name: 'Thomas Lang Signature',
    part_number: 'VIC-TL',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 410,
    diameter_mm: 16.5,
  },
  {
    name: 'Buddy Rich Signature',
    part_number: 'VIC-BR',
    maker: 'VicFirth',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 414,
    diameter_mm: 15.0,
  },
  {
    name: 'Gavin Harrison Signature',
    part_number: 'VIC-HAR2',
    maker: 'VicFirth',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 429,
    diameter_mm: 16.0,
  },
  {
    name: 'Steve Jordan Signature',
    part_number: 'VIC-JOR',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 419,
    diameter_mm: 13.3,
  },
  {
    name: 'Keith Carlock Signature',
    part_number: 'VIC-SKC',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 406,
    diameter_mm: 14.1,
  },
  {
    name: 'Questlove Signature',
    part_number: 'VIC-SAT2',
    maker: 'VicFirth',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 431,
    diameter_mm: 13.2,
  },
  {
    name: 'Tommy Igoe Signature',
    part_number: 'VIC-STI',
    maker: 'VicFirth',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Long',
    length_mm: 409,
    diameter_mm: 14.1,
  },
  {
    name: 'Tony Royster Jr. Signature',
    part_number: 'VIC-STR',
    maker: 'VicFirth',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 409,
    diameter_mm: 13.9,
  },
  {
    name: 'Steve Smith Signature',
    part_number: 'VIC-SSS',
    maker: 'VicFirth',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Short',
    length_mm: 406,
    diameter_mm: 14.1,
  },
  {
    name: 'Stanton Moore Signature',
    part_number: 'VIC-SSM',
    maker: 'VicFirth',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 413,
    diameter_mm: 13.9,
  },
] as const;
