import { DrumStick } from '../if.ts';

export const sticksWincent: ReadonlyArray<DrumStick> = [
  {
    name: '5A',
    part_number: 'W-5A',
    maker: 'Wincent',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 14.3,
  },
  {
    name: '5A XL',
    part_number: 'W-5AXL',
    maker: 'Wincent',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 420,
    diameter_mm: 14.3,
  },
  {
    name: '5A Jazz',
    part_number: 'W-5AJ',
    maker: 'Wincent',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.3,
  },
  {
    name: '5A BARREL TIP',
    part_number: 'W-5ABT',
    maker: 'Wincent',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 14.3,
  },
  {
    name: '5A MAPLE',
    part_number: 'W-5AM',
    maker: 'Wincent',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 14.3,
  },
  {
    name: '5B',
    part_number: 'W-5B',
    maker: 'Wincent',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: '5B XL',
    part_number: 'W-5BXL',
    maker: 'Wincent',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 420,
    diameter_mm: 15.0,
  },
  {
    name: '5B BARREL TIP',
    part_number: 'W-5BBT',
    maker: 'Wincent',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 15.0,
  },
  {
    name: 'SD2',
    part_number: 'W-SD2',
    maker: 'Wincent',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 397,
    diameter_mm: 15.8,
  },
  {
    name: 'SD4',
    part_number: 'W-SD4',
    maker: 'Wincent',
    tip_shape: 'Barrel',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'Mikkey Dee Signature',
    part_number: 'W-MDS',
    maker: 'Wincent',
    tip_shape: 'Teardrop',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 410,
    diameter_mm: 15.8,
  },
  {
    name: 'Tomas Haake Signature',
    part_number: 'W-THS',
    maker: 'Wincent',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 416,
    diameter_mm: 16.2,
  },
  {
    name: 'AKANE［BAND-MAID］Signature',
    part_number: 'W-AKN',
    maker: 'Wincent',
    tip_shape: 'Acorn',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Medium',
    length_mm: 406,
    diameter_mm: 15.0,
  },
] as const;
