import { DrumStick } from '../if.ts';

export const sticksYamaha: ReadonlyArray<DrumStick> = [
  {
    name: 'YS5A',
    part_number: 'YS5A',
    maker: 'Yamaha',
    tip_shape: 'Oval',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.5,
  },
  {
    name: 'YS7A',
    part_number: 'YS7A',
    maker: 'Yamaha',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 394,
    diameter_mm: 14,
  },
  {
    name: 'YS2BN',
    part_number: 'YS2BN',
    maker: 'Yamaha',
    tip_shape: 'Oval',
    tip_material: 'Nylon',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 16.0,
  },

  // Sig.
  {
    name: 'O-JIRO Signature',
    part_number: 'YCSOJ',
    maker: 'Yamaha',
    tip_shape: 'Unknown',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 406,
    diameter_mm: 14.0,
  },
  {
    name: 'George Otsuka Signature',
    part_number: 'YCSGO',
    maker: 'Yamaha',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Hickory',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 16.0,
  },
  {
    name: 'Masahiko Ohsaka Signature',
    part_number: 'YSCSMO2',
    maker: 'Yamaha',
    tip_shape: 'Round',
    tip_material: 'Wood',
    material: 'Maple',
    taper: 'Unknown',
    length_mm: 400,
    diameter_mm: 15.0,
  },
] as const;
