import { DrumStick } from "../if.ts";

export const sticksZildjian: ReadonlyArray<DrumStick> = [
    {
        name: "5A Natural",
        part_number: "LAZLZ5A",
        maker: "Zildjian",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.2,
    },
    {
        name: "5A Natural Nylon",
        part_number: "LAZLZ5AN",
        maker: "Zildjian",
        tip_shape: "Oval",
        tip_material: "Nylon",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 14.2,
    },
    {
        name: "5B Natural",
        part_number: "LAZLZ5B",
        maker: "Zildjian",
        tip_shape: "Teardrop",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 15.2,
    },
    {
        name: "5B Natural Nylon",
        part_number: "LAZLZ5BN",
        maker: "Zildjian",
        tip_shape: "Teardrop",
        tip_material: "Nylon",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 15.2,
    },
    {
        name: "7A Natural",
        part_number: "LAZLZ7A",
        maker: "Zildjian",
        tip_shape: "Round",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 13.2,
    },
    {
        name: "7A Natural Nylon",
        part_number: "LAZLZ7AN",
        maker: "Zildjian",
        tip_shape: "Oval",
        tip_material: "Nylon",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 13.2,
    },
    {
        name: "5B Natural",
        part_number: "LAZLZ2B",
        maker: "Zildjian",
        tip_shape: "Oval",
        tip_material: "Wood",
        material: "Hickory",
        taper: "Unknown",
        length_mm: 406,
        diameter_mm: 15.9,
    },
] as const;